[versions]
project-version = "1.0.0"
kotlin = "2.3.10"
shadow = "9.3.2"
paper-api = "26.2.build.+"
paperweight = "2.0.0-beta.21"
test-paper = "1.21.11-R0.1-SNAPSHOT"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
folia-api = { module = "dev.folia:folia-api", version.ref = "paper-api" }
paperweight = { module = "io.papermc.paperweight:paperweight-userdev", version.ref = "paperweight" }
nyana-nbt = { module = "net.nyana:nyana-nbt-tag", version = "1.0.0" }
nyana-nbt-codec = { module = "net.nyana:nyana-nbt-codec", version = "1.0.0" }
nyana-reflection = { module = "net.nyana:nyana-reflection", version = "1.0.2" }

asm = { module = "org.ow2.asm:asm", version = "9.9.1" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version = "4.106.1" }
test-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "test-paper" }
